In [16]:
#Import library
import pandas as pd
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.model_selection import train_test_split
import os

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
#Load the data
df = pd.read_csv(r'C:\spam-detection\data\raw\sms_spam_dataset.csv', encoding='latin-1')
df.columns = ['label', 'message']
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#Function to clean the text
stemmer= PorterStemmer()
stop_words=set(stopwords.words('english'))

def clean_text(text):
    #Make lowercase
    text=text.lower()
    #Remove number and punctuation
    text=re.sub(r'[^a-z\s]','',text)
    #Seperate words
    words=text.split()
    #Remove stopwords and do stemming
    words=[stemmer.stem(w) for w in words if w not in stop_words]
    return ' '.join(words)

In [ ]:
# Test function with an example
test = "FREE entry! Win a cash prize! Click now!!!"
print(clean_text(test))

free entri win cash prize click

In [8]:
#Apply into full dataset
df['clean_message']=df['message'].apply(clean_text)
df[['message','clean_message']].head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though

In [10]:
#Convert lavel into number
# spam = 1, ham = 0
df['label_num']=df['label'].map({'spam':1, 'ham':0})
df.head()

,label,message,clean_message,label_num
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...,0
1,ham,Ok lar... Joking wif u oni...,ok lar joke wif u oni,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...,1
3,ham,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though,0

In [14]:
# Do train test split
x=df['clean_message']
y=df['label_num']
x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size=0.2,random_state=42
)

print(f'Train size:{len(x_train)}')
print(f'Test size:{len(x_test)}')

Train size:4457
Test size:1115

In [26]:
# Save the processed data

if os.getcwd().endswith('notebooks'):
    os.chdir('..')

output_dir=os.path.join('data','processed')

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

train_df=pd.DataFrame({'message': x_train, 'label':y_train})
test_df=pd.DataFrame({'message':x_test, 'label':y_test})

train_df.to_csv(os.path.join(output_dir,'train.csv'),index=False)
test_df.to_csv(os.path.join(output_dir,'test.csv'),index=False)

print('Data saved!')

Data saved!